name: Android Build

on:
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Gradle
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assemble with Gradle
      run: ./gradlew assemble
    - uses: actions/upload-artifact@v2
      name: Upload AAR Library
      with:
        name: Internal App Android Build APK
        path: |
          GPlay_Billing/build/outputs/aar/GPlay_Billing-release.aar
          GPlay_Billing/build/outputs/aar/GPlay_Billing-debug.aar
